### ISSUE TITLE
access request

### ISSUE THREAD

**Issue by david-humble** [pdhammond42/weavedreamer#2]
Hi Peter can I have access to create a new branch for uploading my new code with proposals for new features

**Comment by pdhammond42** [comment]
Hi David, 
I think the way it's supposed to work is you push to your fork, and then create a pull request for me to merge it.
Although I've been using Git in the day job for years I'm new to GitHub, but I think it is pretty clear when you try it.

**Comment by david-humble** [comment]
Sorted ,  Fork created for new work to be done
